package edu.uade.cookingrecipes.entity.enums;

public enum DishTypes {
    ENTRADA, PLATO_PRINCIPAL, POSTRE, GUARNICION, ENSALADA, SOPA, PAN, PASTA, ARROZ, PESCADO, MARISCOS, AVES, CARNE,
    VEGETARIANO, VEGANO, CELIACO, DESAYUNO, MERIENDA, SNACK, BEBIDA, LICUADO, BATIDO, COCTEL, SALSA, ADEREZO, OTRO,
    TARTA, EMPANADA, PIZZA, HAMBURGUESA, SANDWICH, CEREAL, FRUTA, HELADO, INFUSION, PICADA, GUISO, ESTOFADO, CREMA,
    WOK, TAPAS, CURRY, CROQUETA, MOUSSE, BUDIN, TORTA, GALLETA, BIZCOCHUELO, MILANESA, ROLL, BROCHETA

}
